Repository qexat/magic-list, pull requests merged in 2024-04, with the labels that each got.

#16 feat: add `flatten` method (includes docstring + tests)
  magic_list/prelude.py
  magic_list/prelude.pyi
  tests/list_test.py
Labels: feat, area: test

#19 fix: merge `if`s
  magic_list/prelude.py
Labels: cleanup

#20 doc: add documentation
  docs/index.html
  docs/magic_list.html
  docs/search.js
  magic_list/__init__.py
  magic_list/prelude.py
  magic_list/prelude.pyi
  pyproject.toml
Labels: area: doc

#21 doc: add docs link to readme
  README.md
Labels: area: doc

#22 Bump to 2.1.0
  pyproject.toml
Labels: area: meta

#23 Create upload.yml
  .github/workflows/upload.yml
Labels: area: meta

#24 Create tests.yml
  .github/workflows/tests.yml
Labels: area: meta

#25 doc: add badges
  README-dev.md
  README.md
Labels: area: doc

#26 meta: add dependabot
  .github/dependabot.yml
Labels: area: meta

#28 Soft rename of `gap_fill` to `interleave`
  docs/magic_list.html
  docs/search.js
  magic_list/prelude.py
  magic_list/prelude.pyi
  tests/list_test.py
Labels: area: doc, cleanup

#29 fix: minor fixes for type stubs
  magic_list/prelude.pyi
Labels: cleanup, fix, area: stubs

#30 fix: some docs and type stubs were incorrect
  magic_list/prelude.py
  magic_list/prelude.pyi
Labels: area: doc, cleanup, fix, area: stubs

#33 fix: `interleave` behavior for lists of length 1
  magic_list/prelude.py
  tests/list_test.py
Labels: fix

#34 fix: naming inconsistencies
  magic_list/prelude.py
Labels: area: doc, cleanup

#35 fix: type stub issues
  magic_list/prelude.pyi
Labels: area: stubs

#36 Add docs build workflow
  .github/workflows/build_docs.yml
Labels: area: meta

#37 Improve dev workflow
  .github/workflows/ruff.yml
  .github/workflows/typechecking.yml
  README-dev.md
  pyproject.toml
Labels: area: meta

#40 GH-39: add `min` and `max` methods
  magic_list/prelude.py
  magic_list/prelude.pyi
  tests/list_test.py
Labels: area: doc, feat, area: test, area: stubs

#41 Make docs build on commit to `main` as well
  .github/workflows/build_docs.yml
Labels: area: doc, area: meta

#42 meta: remove build docs workflow
  .github/workflows/build_docs.yml
Labels: area: meta

#45 doc: build
  docs/magic_list.html
  docs/search.js
Labels: area: doc

#46 doc: build
  docs/magic_list.html
Labels: area: doc

#48 meta: add build docs workflow
  .github/workflows/build_docs.yml
Labels: area: meta

#51 doc: add readme contributing section
  README.md
Labels: area: doc

#53 Fix `.shuffled()`
  magic_list/prelude.py
  tests/list_test.py
Labels: fix

#57 fix: harden ruff rules + linting issues
  magic_list/__init__.py
  magic_list/prelude.py
  magic_list/prelude.pyi
  pyproject.toml
  tests/list_test.py
Labels: cleanup

#62 meta: add security policy
  SECURITY.md
Labels: area: meta

#63 meta: add feature request template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature-request.md
Labels: area: meta
